services:
  - type: web
    name: deploy-with-yaml
    env: python
    plan: free
    buildCommand: "poetry install"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    pythonVersion: "3.11.7"